onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
catalog:
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-devtools': ^0.2.2
  '@tanstack/react-router': ^1.130.2
  '@tanstack/react-router-devtools': ^1.131.5
  '@tanstack/router-plugin': ^1.121.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@types/node': ^24.3.0
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@vitejs/plugin-react': ^4.3.4
  jsdom: ^26.0.0
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.0.0
  react-ascii-text: ^0.0.4
  react-cosmos: ^7.0.0
  react-cosmos-plugin-vite: ^7.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.0.6
  typescript: ^5.7.2
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  web-vitals: ^4.2.4
