/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoodCheckInRouteImport } from './routes/mood-check-in'
import { Route as InstantTaskSortRouteImport } from './routes/instant-task-sort'
import { Route as EnergyAwareAgendaRouteImport } from './routes/energy-aware-agenda'
import { Route as IndexRouteImport } from './routes/index'

const MoodCheckInRoute = MoodCheckInRouteImport.update({
  id: '/mood-check-in',
  path: '/mood-check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InstantTaskSortRoute = InstantTaskSortRouteImport.update({
  id: '/instant-task-sort',
  path: '/instant-task-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyAwareAgendaRoute = EnergyAwareAgendaRouteImport.update({
  id: '/energy-aware-agenda',
  path: '/energy-aware-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/energy-aware-agenda': typeof EnergyAwareAgendaRoute
  '/instant-task-sort': typeof InstantTaskSortRoute
  '/mood-check-in': typeof MoodCheckInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/energy-aware-agenda': typeof EnergyAwareAgendaRoute
  '/instant-task-sort': typeof InstantTaskSortRoute
  '/mood-check-in': typeof MoodCheckInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/energy-aware-agenda': typeof EnergyAwareAgendaRoute
  '/instant-task-sort': typeof InstantTaskSortRoute
  '/mood-check-in': typeof MoodCheckInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/energy-aware-agenda'
    | '/instant-task-sort'
    | '/mood-check-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/energy-aware-agenda' | '/instant-task-sort' | '/mood-check-in'
  id:
    | '__root__'
    | '/'
    | '/energy-aware-agenda'
    | '/instant-task-sort'
    | '/mood-check-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnergyAwareAgendaRoute: typeof EnergyAwareAgendaRoute
  InstantTaskSortRoute: typeof InstantTaskSortRoute
  MoodCheckInRoute: typeof MoodCheckInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mood-check-in': {
      id: '/mood-check-in'
      path: '/mood-check-in'
      fullPath: '/mood-check-in'
      preLoaderRoute: typeof MoodCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instant-task-sort': {
      id: '/instant-task-sort'
      path: '/instant-task-sort'
      fullPath: '/instant-task-sort'
      preLoaderRoute: typeof InstantTaskSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-aware-agenda': {
      id: '/energy-aware-agenda'
      path: '/energy-aware-agenda'
      fullPath: '/energy-aware-agenda'
      preLoaderRoute: typeof EnergyAwareAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnergyAwareAgendaRoute: EnergyAwareAgendaRoute,
  InstantTaskSortRoute: InstantTaskSortRoute,
  MoodCheckInRoute: MoodCheckInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
